### ISSUE TITLE
Why GenServer?

### ISSUE THREAD

**Issue by cvkmohan** [codylandry/ex_chat#1]
This is not an issue - rather a question mainly to know your viewpoint.
Instead of using plain context - you made the Chat a GenServer. Is it only for a learning purpose? Any idea on what are the pros and cons of going through that approach?

Secondly, a small feedback. By moving the SEND_IN_BLUE config from `config.exs` to `prod.exs` you would be reducing one hurdle for some one who wants to try the app in dev mode.

Thanks.

**Comment by codylandry** [comment]
Hi!  I was loosely following a course I bought (https://www.knowthen.com/elixir-and-phoenix-for-beginners).   They built a exit polling application using a similar approach.   The idea was for the live updates to be as fast as possible, so in memory in a genserver.   That's why I offloaded database updates to an async Task process where possible, which will sort of reset the genserver state if there's an issue updating the db.  I'm totally new to elixir and phoenix so I'm totally open to advice, opinions and tips!

> Secondly, a small feedback. By moving the SEND_IN_BLUE config from config.exs to prod.exs you would be reducing one hurdle for some one who wants to try the app in dev mode.

That makes sense.  How would the mailer work in dev mode?  Would you just log out the messages?

**Comment by cvkmohan** [comment]
Thanks for the quick response.

Regarding the mails - 
In the dev mode, `config :ex_chat, ExChat.Mailer, adapter: Swoosh.Adapters.Local` is what can be kept in `config.exs` 
This will make the mails accessible at a url `/dev/mailbox`

**Comment by codylandry** [comment]
Oh nice.  I didn't know that.  👍
